# Generated by Django 3.1.1 on 2020-09-03 02:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='date_of_birth',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Date of Birth'),
            preserve_default=False,
        ),
    ]
