version: "3.8"

services:
    web:
        build: .
        command: python manage.py runserver 0.0.0.0:8000
        volumes:
            - .:/code
        ports:
            - "8000:8000"
        depends_on:
            - db
    db:
        image: postgres
        restart: always
        ports:
            - "5432:5432"
        volumes:
            - $HOME/docker/volumes/postgres:/var/lib/postgresql/data
