# Generated by Django 3.1.1 on 2020-09-12 20:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter item name', max_length=128, verbose_name='Item name')),
                ('price', models.DecimalField(decimal_places=2, help_text='Enter item price', max_digits=7, verbose_name='Item price')),
                ('size', models.CharField(choices=[('N/A', 'N/A'), ('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL')], default='N/A', help_text='Select the size', max_length=5, verbose_name='Item size')),
                ('color', models.CharField(choices=[('Red', 'Red'), ('Orange', 'Orange'), ('Yellow', 'Yellow'), ('Green', 'Green'), ('Cyan', 'Cyan'), ('Azure', 'Azure'), ('Blue', 'Blue'), ('Violet', 'Violet'), ('Magenta', 'Magenta'), ('Rose', 'Rose')], default='N/A', help_text='Select the color', max_length=20, verbose_name='Item color')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
