# Generated by Django 3.1.1 on 2020-09-12 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='color',
            field=models.CharField(choices=[('N/A', 'N/A'), ('Red', 'Red'), ('Orange', 'Orange'), ('Yellow', 'Yellow'), ('Green', 'Green'), ('Cyan', 'Cyan'), ('Azure', 'Azure'), ('Blue', 'Blue'), ('Violet', 'Violet'), ('Magenta', 'Magenta'), ('Rose', 'Rose')], default='N/A', help_text='Select the color', max_length=20, verbose_name='Item color'),
        ),
    ]
